### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Krato** [danmacnish/cartoonify#9]
Hi, I installed but I don't know how to run it.

I show you my terminal session: https://asciinema.org/a/n8VjH60sHnF4SUFGgwiVPXqgR

And the log:

```
ERROR:No module named RPi.GPIO
Traceback (most recent call last):
  File "/Users/ericlagarda/Downloads/cartoonify-master/cartoonify/app/gpio/gpio.py", line 16, in __init__
    self.gpio = importlib.import_module('RPi.GPIO')
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named RPi.GPIO
INFO:loading cartoon dataset...
INFO:Done
INFO:loading tensorflow model...
INFO:Done
INFO:setup finished.
INFO:processing image...
INFO:saving results...
```

Thanks so much!

**Comment by danmacnish** [comment]
@Krato hmm, that definitely hasn't occurred for me. Seems like it's not parsing your input correctly. I'm really just guessing here, but try changing any mentions of `input()` to `raw_input()` - particularly line 86 of `run.py`:

```python
                path = Path(input("enter the filepath of the image to process:"))
```
